@extends('layouts.foodbank')

@section('title', 'Impact Reports | SavEats')

@section('header', 'Impact Reports')

@section('styles')
<link href="https://fonts.googleapis.com/css2?family=Afacad:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('css/foodbank-impact-reports.css') }}">
@endsection

@section('content')
<div class="foodbank-impact-reports-container">
    <!-- Stats Cards Row -->
    <div class="stats-row">
        <div class="stats-card orange">
            <h3>Food Requests</h3>
            <div class="value">{{ $foodRequests ?? 0 }}</div>
        </div>
        <div class="stats-card yellow">
            <h3>Food Received</h3>
            <div class="value">{{ $foodReceived ?? 0 }}</div>
        </div>
    </div>

    <!-- Action Buttons -->
    <div class="action-buttons">
        <button class="btn btn-primary" id="exportBtn">
            <svg viewBox="0 0 24 24">
                <path d="M19 12v7H5v-7H3v7c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-7h-2zm-6 .67l2.59-2.58L17 11.5l-5 5-5-5 1.41-1.41L11 12.67V3h2z"/>
            </svg>
            Export Report
        </button>
    </div>

    <!-- Charts Grid -->
    <div class="charts-grid">
        <!-- Monthly Food Saved Chart -->
        <div class="chart-card">
            <div class="chart-header">
                <div class="chart-header-left">
                    <div class="chart-tabs">
                        <button class="tab-btn" data-tab="daily">Daily</button>
                        <button class="tab-btn active" data-tab="monthly">Monthly</button>
                        <button class="tab-btn" data-tab="yearly">Yearly</button>
                    </div>
                </div>
                <h2 class="chart-title">MONTHLY FOOD SAVED</h2>
            </div>
            <div class="chart-container">
                <canvas id="foodSavedChart"></canvas>
            </div>
            <div class="chart-legend">
                <div class="legend-item">
                    <div class="legend-color"></div>
                    <span>Number of items saved</span>
                </div>
            </div>
        </div>

        <!-- Top Establishment Contributors -->
        <div class="chart-card">
            <div class="chart-header">
                <h2 class="chart-title">Top Establishment Contributors</h2>
            </div>
            <div class="chart-container">
                <div class="contributors-list" id="contributorsList">
                    <!-- Contributors will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>

    <!-- Reports Table -->
    <div class="reports-section">
        <div class="section-header">
            <h3 class="section-title">Generated Reports</h3>
        </div>

        <table class="reports-table">
            <thead>
                <tr>
                    <th>Report Name</th>
                    <th>Date Generated</th>
                    <th>Period</th>
                    <th>Format</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="reportsTableBody">
                @if(isset($reports) && count($reports) > 0)
                    @foreach($reports as $report)
                    <tr>
                        <td data-label="Report Name">{{ $report['name'] }}</td>
                        <td data-label="Date Generated">{{ $report['date'] }}</td>
                        <td data-label="Period">{{ $report['period'] }}</td>
                        <td data-label="Format">{{ $report['format'] }}</td>
                        <td data-label="Action">
                            <button class="download-btn" onclick="downloadReport('{{ $report['name'] }}')">
                                <svg viewBox="0 0 24 24">
                                    <path d="M19 12v7H5v-7H3v7c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-7h-2zm-6 .67l2.59-2.58L17 11.5l-5 5-5-5 1.41-1.41L11 12.67V3h2z"/>
                                </svg>
                                Download
                            </button>
                        </td>
                    </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="5" style="text-align: center; padding: 40px; color: #9ca3af;">
                            No reports generated yet. Export a report to see it here.
                        </td>
                    </tr>
                @endif
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    // Pass chart data to JavaScript
    window.chartData = {
        daily: @json($dailyData ?? []),
        monthly: @json($monthlyData ?? []),
        yearly: @json($yearlyData ?? [])
    };
    window.topContributorsData = @json($topContributorsData ?? []);
</script>
<script src="{{ asset('js/foodbank-impact-reports.js') }}"></script>
@endsection

