@extends('layouts.foodbank')

@section('title', 'Impact Reports | SavEats')

@section('header', 'Impact Reports')

@section('styles')
<link href="https://fonts.googleapis.com/css2?family=Afacad:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('css/foodbank-impact-reports.css') }}">
@endsection

@section('content')
<div class="foodbank-impact-reports-container">
    <!-- Stats Cards Row -->
    <div class="stats-row">
        <div class="stats-card orange">
            <h3>Food Requests</h3>
            <div class="value">{{ $foodRequests ?? 0 }}</div>
        </div>
        <div class="stats-card yellow">
            <h3>Food Received</h3>
            <div class="value">{{ $foodReceived ?? 0 }}</div>
        </div>
        <div class="stats-card green">
            <h3>Families Served</h3>
            <div class="value">{{ $familiesServed ?? 0 }}</div>
        </div>
        <div class="stats-card blue">
            <h3>Total Impact Score</h3>
            <div class="value">{{ $totalImpactScore ?? 0 }}%</div>
        </div>
    </div>

    <!-- Action Buttons -->
    <div class="action-buttons">
        <button class="btn btn-primary" id="exportBtn">
            <svg viewBox="0 0 24 24">
                <path d="M19 12v7H5v-7H3v7c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-7h-2zm-6 .67l2.59-2.58L17 11.5l-5 5-5-5 1.41-1.41L11 12.67V3h2z"/>
            </svg>
            Export Report
        </button>
        <button class="btn btn-secondary" id="shareBtn">
            <svg viewBox="0 0 24 24">
                <path d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92 1.61 0 2.92-1.31 2.92-2.92s-1.31-2.92-2.92-2.92z"/>
            </svg>
            Share
        </button>
        <button class="btn btn-secondary" id="printBtn">
            <svg viewBox="0 0 24 24">
                <path d="M19 8H5c-1.66 0-3 1.34-3 3v6h4v4h12v-4h4v-6c0-1.66-1.34-3-3-3zm-3 11H8v-5h8v5zm3-7c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1zm-1-9H6v4h12V3z"/>
            </svg>
            Print
        </button>
    </div>

    <!-- Charts Grid -->
    <div class="charts-grid">
        <!-- Monthly Food Saved Chart -->
        <div class="chart-card">
            <div class="chart-header">
                <div class="chart-header-left">
                    <div class="chart-tabs">
                        <button class="tab-btn" data-tab="daily">Daily</button>
                        <button class="tab-btn active" data-tab="monthly">Monthly</button>
                        <button class="tab-btn" data-tab="yearly">Yearly</button>
                    </div>
                </div>
                <h2 class="chart-title">MONTHLY FOOD SAVED</h2>
            </div>
            <div class="chart-container">
                <canvas id="foodSavedChart"></canvas>
            </div>
            <div class="chart-legend">
                <div class="legend-item">
                    <div class="legend-color"></div>
                    <span>Number of items saved</span>
                </div>
            </div>
        </div>

        <!-- Top Establishment Contributors -->
        <div class="chart-card">
            <div class="chart-header">
                <h2 class="chart-title">Top Establishment Contributors</h2>
            </div>
            <div class="chart-container">
                <div class="contributors-list" id="contributorsList">
                    <!-- Contributors will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>

    <!-- Reports Table -->
    <div class="reports-section">
        <div class="section-header">
            <h3 class="section-title">Generated Reports</h3>
        </div>

        <table class="reports-table">
            <thead>
                <tr>
                    <th>Report Name</th>
                    <th>Date Generated</th>
                    <th>Period</th>
                    <th>Format</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="reportsTableBody">
                @foreach($reports ?? [] as $report)
                <tr>
                    <td data-label="Report Name">{{ $report['name'] }}</td>
                    <td data-label="Date Generated">{{ $report['date'] }}</td>
                    <td data-label="Period">{{ $report['period'] }}</td>
                    <td data-label="Format">{{ $report['format'] }}</td>
                    <td data-label="Action">
                        <button class="download-btn" onclick="downloadReport('{{ $report['name'] }}')">
                            <svg viewBox="0 0 24 24">
                                <path d="M19 12v7H5v-7H3v7c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-7h-2zm-6 .67l2.59-2.58L17 11.5l-5 5-5-5 1.41-1.41L11 12.67V3h2z"/>
                            </svg>
                            Download
                        </button>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    // Pass chart data to JavaScript
    window.chartData = {
        daily: @json($dailyData ?? []),
        monthly: @json($monthlyData ?? []),
        yearly: @json($yearlyData ?? [])
    };
    window.topContributorsData = @json($topContributorsData ?? []);
</script>
<script src="{{ asset('js/foodbank-impact-reports.js') }}"></script>
@endsection

